User.create({name: 'APresent', email: 'apresent@simplon.co', password: 'present', password_confirmation: 'present', student_type: User::LOCAL})
User.create({name: 'BPresent', email: 'bpresent@simplon.co', password: 'present', password_confirmation: 'present', student_type: User::LOCAL})
User.create({name: 'CPresent', email: 'cpresent@simplon.co', password: 'present', password_confirmation: 'present', student_type: User::LOCAL})
User.create({name: 'DPresent', email: 'dpresent@simplon.co', password: 'present', password_confirmation: 'present', student_type: User::LOCAL})
User.create({name: 'Distant', email: 'distant@simplon.co', password: 'distant', password_confirmation: 'distant', student_type: User::REMOTE})
Exercice.create({consigne: "Ceci est l'exercice 1", echantillon: 'some string JSON', reponse: 'some string JSON', format_reponse: 1, titre: 'baz', format_echantillon: '1'})
Exercice.create({consigne: "Ceci est l'exercice 2", echantillon: 'foo', reponse: 'bar', format_reponse: 2, titre: 'baz', format_echantillon: '2'})
Exercice.create({consigne: "Ceci est l'exercice 3", echantillon: 'foo', reponse: 'bar', format_reponse: 3, titre: 'baz', format_echantillon: '3'})
Lesson.create({title: "Premiere lecon Ruby", online: true})
Chapter.create({lesson_id: 1, title: "Ruby", content: "Ruby is the best ruby"})
Definition.create({keyword: "ruby", description: "the best", url: "https://www.ruby-lang.org"})